driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: win2012r2
    run_list:
    driver_config:
      box: opentable/win-2012r2-standard-amd64-nocm
  - name: win2008r2
    run_list:
    driver_config:
      box: opentable/win-2008r2-standard-amd64-nocm

suites:
  - name: smoke_test
    run_list:
      - recipe[iis::default]
      - recipe[test_helper::default]
